name: build-world-no-pch
on:
  push:
    branches:
      - 'master'  # only default branch
  pull_request:

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # the result of the matrix will be the combination of all attributes, so we get os*compiler*modules builds
        os: [ubuntu-latest]
        compiler: [clang12]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.compiler }}
    env:
      COMPILER: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: var/ccache
          key: ccache:${{ matrix.os }}:${{ matrix.compiler }}:${{ github.ref }}:${{ github.sha }}:world
          restore-keys: |
            ccache:${{ matrix.os }}:${{ matrix.compiler }}:${{ github.ref }}:world
            ccache:${{ matrix.os }}:${{ matrix.compiler }}:world
      - name: Configure OS
        run: source ./acore.sh install-deps
        env:
          CONTINUOUS_INTEGRATION: true
      - name: Create conf/config.sh
        run: source ./apps/ci/ci-configure-world.sh static OFF OFF
      - name: Build
        run: source ./apps/ci/ci-compile.sh
      - name: Dry run
        run: source ./apps/ci/ci-dry-run.sh worldserver
